programa: alinear.cpp canvas.cpp esfera.cpp janela.cpp raio.cpp main.cpp
	g++ -o programa externo/alinear.cpp tela/canvas.cpp ray/raio.cpp objetos/esfera.cpp objetos/cilindro.cpp objetos/cone.cpp tela/janela.cpp externo/renderizar.cpp main.cpp -lSDL2
