programa: externo/alinear.cpp externo/luz.cpp tela/canvas.cpp ray/raio.cpp objetos/esfera.cpp tela/janela.cpp externo/renderizar.cpp main.cpp
	g++ -o programa externo/alinear.cpp externo/luz.cpp tela/canvas.cpp ray/raio.cpp objetos/esfera.cpp tela/janela.cpp externo/renderizar.cpp main.cpp -lSDL2
